name: Check ebooks

on:
  schedule:
    - cron: '0 8 * * *'
    - cron: '0 20 * * *'

  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install -r requirements.txt

      - name: Run scraper
        env:
          FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          VALIDATION_CHANNEL_ID: ${{ secrets.VALIDATION_CHANNEL_ID }}
          PUBLIC_CHANNEL_ID: ${{ secrets.PUBLIC_CHANNEL_ID }}
        run: python scraper.py

      - name: Save database
        run: |
          git config --global user.name "ebook-bot"
          git config --global user.email "bot@github.com"
          git add seen_books.json ignored_books.json
          git commit -m "Update books" || exit 0
          git push
